language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
after_success:
- grunt gh-pages
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libcairo2-dev
    - libgif-dev
    - graphicsmagick
    - libjpeg8-dev
